<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="SQELabs" failures="1" tests="8" name="BillRunFirst.New_reminder_functionality" time="456.069" errors="0" timestamp="14 May 2018 05:49:40 GMT" skipped="0">
  <testcase classname="BillRunFirst.New_reminder_functionality" name="autogenrate_Four_plans" time="19.179"/>
  <testcase classname="BillRunFirst.New_reminder_functionality" name="Customer_Services_and_mtrNO" time="165.853"/>
  <testcase classname="BillRunFirst.New_reminder_functionality" name="addOnceOffCharges" time="41.241"/>
  <testcase classname="BillRunFirst.New_reminder_functionality" name="addRecurringCharges" time="68.303"/>
  <testcase classname="BillRunFirst.New_reminder_functionality" name="BillRun_Cycle_Customer" time="18.294"/>
  <testcase classname="BillRunFirst.New_reminder_functionality" name="Bill_Run_Customer" time="64.926"/>
  <testcase classname="BillRunFirst.New_reminder_functionality" name="Reminder_section" time="28.336">
    <failure message="expected [1] but found []" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [1] but found []at org.testng.Assert.fail(Assert.java:96)at org.testng.Assert.failNotEquals(Assert.java:776)at org.testng.Assert.assertEqualsImpl(Assert.java:137)at org.testng.Assert.assertEquals(Assert.java:118)at org.testng.Assert.assertEquals(Assert.java:453)at org.testng.Assert.assertEquals(Assert.java:463)at Re_usable.Assertion_Test.ChangesReminder(Assertion_Test.java:1546)at BillRunFirst.New_reminder_functionality.Reminder_section(New_reminder_functionality.java:596)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)at java.base/java.lang.reflect.Method.invoke(Unknown Source)at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)at org.testng.internal.Invoker.invokeMethod(Invoker.java:571)at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:707)at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:979)at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)at org.testng.TestRunner.privateRun(TestRunner.java:648)at org.testng.TestRunner.run(TestRunner.java:505)at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)at org.testng.SuiteRunner.run(SuiteRunner.java:364)at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)at org.testng.TestNG.runSuitesSequentially(TestNG.java:1187)at org.testng.TestNG.runSuitesLocally(TestNG.java:1116)at org.testng.TestNG.runSuites(TestNG.java:1028)at org.testng.TestNG.run(TestNG.java:996)at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)]]>
    </failure>
  </testcase> <!-- Reminder_section -->
  <testcase classname="BillRunFirst.New_reminder_functionality" name="Genrate_Reminders" time="49.937"/>
</testsuite> <!-- BillRunFirst.New_reminder_functionality -->
